
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

lovelace:
  dashboards:
    lovelace:
      mode: yaml
      filename: ui-lovelace.yaml
      title: Overview
      icon: mdi:view-dashboard
      show_in_sidebar: true

input_button:
  licht_an:
    name: Licht An

rest: !include configuration/rest/rest.yaml

rest_command: !include configuration/rest/rest_commands.yaml

template: !include_dir_merge_list configuration/template/

light: !include configuration/lights/lights.yaml

cover: !include configuration/cover/covers.yaml
