title: Home
views:
  - title: Steuerung
    path: steuerung
    cards:
      - type: tile
        entity: cover.raffstore_wohnzimmer_west
        name: Raffstore Wohnzimmer West
        icon: mdi:window-shutter
        state_content:
          - state
          - position
        features:
          - type: cover-open-close
          - type: cover-position
          - type: cover-tilt-position
      - type: entities
        title: Raffstore Sensoren
        entities:
          - entity: sensor.raffstore_position
            name: Behang Position (M13)
          - entity: sensor.raffstore_lamelle
            name: Lamellen Position (M14)
