title: Home
views:
  - title: Steuerung
    path: steuerung
    cards:
      - type: tile
        entity: cover.eg_raffstores_zentral_gruppe
        name: Alle Raffstores runterfahren
        icon: mdi:window-shutter
        features:
          - type: cover-open-close
          - type: cover-position
      - type: tile
        entity: cover.raffstore_wohnzimmer_west
        name: Raffstore Wohnzimmer West
        icon: mdi:window-shutter
        state_content:
          - state
          - position
        features:
          - type: cover-open-close
          - type: cover-position
          - type: cover-tilt-position
      - type: tile
        entity: cover.raffstore_wohnzimmer_sued
        name: Raffstore Wohnzimmer Süd
        icon: mdi:window-shutter
        state_content:
          - state
          - position
        features:
          - type: cover-open-close
          - type: cover-position
          - type: cover-tilt-position
      - type: tile
        entity: cover.raffstores_wohnzimmer
        name: Raffstores Wohnzimmer (beide)
        icon: mdi:window-shutter-open
        state_content:
          - state
          - position
        features:
          - type: cover-open-close
          - type: cover-position
      - type: light
        entity: light.led_band_wohnzimmer
        name: LED Band
      - type: light
        entity: light.led_spots_wohnzimmer
        name: LED Spots
      - type: tile
        entity: light.deckenlampe_wohnzimmer
        name: Deckenlampe
        icon: mdi:ceiling-light
      - type: tile
        entity: cover.raffstore_essbereich
        name: Raffstore Essbereich
        icon: mdi:window-shutter
        state_content:
          - state
          - position
        features:
          - type: cover-open-close
          - type: cover-position
          - type: cover-tilt-position
      - type: light
        entity: light.led_band_essbereich
        name: LED Band Essbereich
      - type: light
        entity: light.led_spots_essbereich
        name: LED Spots Essbereich
      - type: tile
        entity: light.deckenlampe_essbereich
        name: Deckenlampe Essbereich
        icon: mdi:ceiling-light
      - type: tile
        entity: cover.raffstore_kuche_ost
        name: Raffstore Küche Ost
        icon: mdi:window-shutter
        state_content:
          - state
          - position
        features:
          - type: cover-open-close
          - type: cover-position
          - type: cover-tilt-position
      - type: tile
        entity: cover.raffstore_kuche_sued
        name: Raffstore Küche Süd
        icon: mdi:window-shutter
        state_content:
          - state
          - position
        features:
          - type: cover-open-close
          - type: cover-position
          - type: cover-tilt-position
      - type: light
        entity: light.led_spots_kuche_vorne
        name: LED Spots Küche Vorne
      - type: light
        entity: light.led_spots_kuche_hinten
        name: LED Spots Küche Hinten
      - type: light
        entity: light.led_spots_kuche
        name: LED Spots Küche (beide)
      - type: entities
        title: Raffstore Sensoren
        entities:
          - entity: sensor.raffstore_position
            name: Behang Position West (M13)
          - entity: sensor.raffstore_lamelle
            name: Lamellen Position West (M14)
          - entity: sensor.raffstore_sued_position
            name: Behang Position Süd (M22)
          - entity: sensor.raffstore_sued_lamelle
            name: Lamellen Position Süd (M23)
  