- platform: group
  name: "Raffstores Wohnzimmer"
  unique_id: raffstores_wohnzimmer_gruppe
  entities:
    - cover.raffstore_wohnzimmer_west
    - cover.raffstore_wohnzimmer_sud

- platform: group
  name: "EG Raffstore Zentral"
  unique_id: eg_raffstores_zentral_gruppe
  entities:
    - cover.raffstore_wohnzimmer_west
    - cover.raffstore_wohnzimmer_sud
    - cover.raffstore_essbereich
    - cover.raffstore_kuche_ost
    - cover.raffstore_kuche_sud

- platform: group
  name: "DG Rolle Zentral"
  unique_id: dg_rolle_zentral_gruppe
  entities:
    - cover.rolladen_kinderzimmer_west
    - cover.rolladen_kinderzimmer_sud_2
    - cover.rolladen_schlafzimmer
